### ISSUE TITLE
RIP build since XML 3.3.0

### ISSUE THREAD

**Issue by jm-parent** [witochandra/webfeed#12]
Hey 

It seems we'll have problem with those changes ( XMLElement => XMLElementEvent .... )
[https://github.com/renggli/dart-xml/commit/4f7a3237752b4488c3b90fdc71e6c788024287cf?diff=unified](url)

I tried with Webfeed 0.4.1 , but breaking changes in XML 3.3.0 ( 16 days ago ) is to damn high ;)
[https://imgur.com/haKpizV.png](url)

Hope we can expect an update 🙏

**Comment by witochandra** [comment]
Thanks for reporting. 
Please update the webfeed package into 0.4.2.

**Comment by jm-parent** [comment]
Perfect , thx a lot 👌
