### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by DewangS** [witochandra/webfeed#13]
I tried your sample code in my main.dart and it's not working. Getting at the below core dart file at findAllElements() call step .......
I've below SDK config in my pubsync ...is this plugin compatible with Dart 2.0 ?

**environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"**

```
import 'dart:core';

import 'package:xml/xml.dart';

XmlElement findElementOrNull(XmlElement element, String name) {
  try {
    return element.findAllElements(name).first;
  } on StateError {
    return null;
  }
}

```

**Comment by zekihocanet** [comment]
this is not webfeed package.
