### ISSUE TITLE
StateError (Bad state: No element)

### ISSUE THREAD

**Issue by vleeuwenmenno** [witochandra/webfeed#15]
This code returns an exception on the last line 
```
    /// Load data from RSS Feed
 		Client client = Client();
		Response response = await client.get("https://www.apple.com/newsroom/rss-feed.rss");
		RssFeed channel;
		String rssXml = response.body;

		channel = RssFeed.parse(rssXml);
```
![image](https://user-images.githubusercontent.com/46482143/59442630-df58f400-8dfa-11e9-8420-22d3af8168a1.png)

Flutter doc
```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.18908.1000], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\Tools\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Tools\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Tools\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)        
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • ONEPLUS A6013 • afa09d33 • android-arm64 • Android 9 (API 28)

• No issues found!```

**Comment by witochandra** [comment]
https://www.apple.com/newsroom/rss-feed.rss

That is atom feed. Please use this `AtomFeed.parse` instead of `RssFeed.parse` :)

**Comment by vleeuwenmenno** [comment]
> https://www.apple.com/newsroom/rss-feed.rss
> 
> That is atom feed. Please use this `AtomFeed.parse` instead of `RssFeed.parse` :)

Oh sorry that was not the RSS feed I was testing on initially.
So that means that this `https://www.anno-union.com/en/feed` is also Atom?

**Comment by witochandra** [comment]
https://www.anno-union.com/en/feed

that one is RssFeed.

**Comment by vleeuwenmenno** [comment]
> https://www.anno-union.com/en/feed
> 
> that one is RssFeed.

Alright, so any idea why it would show up this error?
It works fine if I disable all exceptions on debugging. But when I compile a release build it just doesn't run the code.

**Comment by vleeuwenmenno** [comment]
I have found the issue.
There is a class called Helper
The function there calls first without checking if it is empty or not.
I created a PR that fixes the issue https://github.com/witochandra/webfeed/pull/16
