### ISSUE TITLE
Can you add the <image> element to RSSItem? Many rss feeds have image elements instead of enclosures.

### ISSUE THREAD

**Issue by JulianCurrie** [witochandra/webfeed#17]

**Comment by onuracikgoz** [comment]
we need to <image> tag pls add this function

**Comment by arodriguezgb** [comment]
Any update on this ? THe blog i need to use doesnt have the image inside enclosure either and i cant get the images.

https://blog.gentlebirth.com/?format=rss. <- this is the blog if theres any chance you may know how to access them.

**Comment by pash** [comment]
Hi, I encountered the same issue and I access it using this:

`item.media.contents.length > 0 ? item.media.contents.first.url : "placeholder image",`

I hope that helps.
