### ISSUE TITLE
Doesn't seem to work with feeds produced by Pinboard

### ISSUE THREAD

**Issue by andrewducker** [witochandra/webfeed#21]
var rssFeed = new RssFeed.parse(response.body); on the result of fetching https://feeds.pinboard.in/rss/u:andrewducker/ picks up the description, but not any of the items.

Any idea why?

**Comment by stonega** [comment]
Because the item node is out of channel

**Comment by witochandra** [comment]
That is RDF feed. 

Currently, this package is not supporting that type of feed.

**Comment by andrewducker** [comment]
Thank you for tracking down why it doesn't work. I'll see if I can find an RDF parser!

**Comment by witochandra** [comment]
Try webfeed 0.6.0. 

It supports RDF now.

**Comment by andrewducker** [comment]
Impressive work!

(I'm a bit busy at the moment - baby is due in 2 weeks - but when things calm down again...)
