### ISSUE TITLE
Add support for xml: ^4.1.0

### ISSUE THREAD

**Issue by ripetrescu** [witochandra/webfeed#28]

**Comment by witochandra** [comment]
Upgraded the xml package. 

Try using

```
webfeed: ^0.5.1
```

**Comment by brenodt** [comment]
@witochandra I've tried depending on `webfeed: ^0.5.1`, which returns the following error:

```
Because every version of flutter from sdk depends on meta 1.1.8 and xml >=4.3.0 depends on meta ^1.2.0, flutter from sdk is incompatible with xml >=4.3.0.
And because webfeed >=0.5.0 depends on xml ^4.3.0, flutter from sdk is incompatible with webfeed >=0.5.0.
So, because rss_reader depends on both flutter any from sdk and webfeed 0.5.1, version solving failed.
pub get failed (1; So, because rss_reader depends on both flutter any from sdk and webfeed 0.5.1, version solving failed.)
```

I'm currently using v0.4.2, which doesn't have this incompatibility issue, but I wish to use the latest one. Is there a workaround to this issue?

**Comment by witochandra** [comment]
Oh... Maybe it was to early to use xml `^4.3.0`. 😅 

try `webfeed: ^0.5.2`, I had lowered the xml version constraints into `^0.4.2`.

Or if that is not working, you can try adding the `dependency_overrides` on the xml package. https://dart.dev/tools/pub/dependencies#dependency-overrides
