### ISSUE TITLE
StateError (Bad state: No element)

### ISSUE THREAD

**Issue by francescovallone** [witochandra/webfeed#29]
Hello, I'm trying to parse https://videogamezone.eu/feed.xml but it returns StateError (Bad state: No element) both with RssFeed and AtomFeed
Here is the function I'm using rn:
```dart
Future<AtomFeed> loadFeed() async {
    final client = http.Client();
    final response = await client.get(FEED_URL);
    print(response.body);
    return AtomFeed.parse(response.body);
}

**Comment by witochandra** [comment]
That is a `RssFeed`. 

Seems like I can successfully parse that feed. 

Closing the issue.
