### ISSUE TITLE
Depends on webfeed any which requires SDK version >=1.8.0 <2.0.0, version solving failed

### ISSUE THREAD

**Issue by amendezcabrera** [witochandra/webfeed#3]
This library needs an update to support the new Dart SDK version, it would be nice to upgrade it.

> /.../SDK/Flutter/flutter/bin/flutter --no-color packages upgrade
Running "flutter packages upgrade" in app...
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.
Because app depends on webfeed any which requires SDK version >=1.8.0 <2.0.0, version solving failed.
pub upgrade failed (1)
Process finished with exit code 1

Thank you very much

**Comment by witochandra** [comment]
thanks for reporting. Now this package can be used in dart2

**Comment by witochandra** [comment]
Since `webfeed: ^0.2.2`

**Comment by amendezcabrera** [comment]
I did a fork meanwhile you couldn't update it and was planning to send you a PR but you have been very fast. Thank you very much.
