### ISSUE TITLE
Invalid argument: description not found with Medium feeds

### ISSUE THREAD

**Issue by amendezcabrera** [witochandra/webfeed#4]
Error parsing the feeds from [Medium](https://medium.com/) sources. An example of not working sources (i think they are RSS):
- https://blog.apollographql.com/feed
- https://hackernoon.com/feed

I tried with those two, but if you add /feed to any self-domain medium blog you will notice the library can't parse it, it would be nice if you could fix it.
Thank you

**Comment by witochandra** [comment]
Thanks for reporting this.
Yes. It fails when in the rss-feed / item doesn't have `description` in it.

**Comment by witochandra** [comment]
Use `webfeed: ^0.2.3`.
Now it will not fail again if there are no description in the rss feed / item. :)
