### ISSUE TITLE
Resolving dependencies fail

### ISSUE THREAD

**Issue by javierbm7** [witochandra/webfeed#45]
Hi today with the new Flutter version webfeed fail :(

Because webfeed >=0.5.0 depends on intl ^0.16.0 and every version of flutter_localizations from sdk depends on intl 0.17.0, webfeed >=0.5.0 is incompatible with flutter_localizations from sdk.
So, because oci_balance_app depends on both flutter_localizations any from sdk and webfeed ^0.6.0, version solving failed.
pub get failed (1; So, because oci_balance_app depends on both flutter_localizations any from sdk and webfeed ^0.6.0, version solving failed.)

**Comment by mukhtarfauzi** [comment]
use my forking repo https://github.com/mukhtarfauzi/webfeed/tree/intl-upgrade
I already make a PR

**Comment by witochandra** [comment]
Some dependencies have been upgraded.
