### ISSUE TITLE
No "enclosure" tag supported

### ISSUE THREAD

**Issue by matthew-carroll** [witochandra/webfeed#7]
Hi, I'm trying to parse a Podcast RSS feed that uses `<enclosure>` tags to define the URL that hosts the MP3 file.  As far as I can tell there is no support for that tag in webfeed.  Is there any particular reason why?

**Comment by witochandra** [comment]
Thanks for reporting. 

Added support to `enclosure` tag in `webfeed: ^0.4.0`
