### ISSUE TITLE
A more complete example?

### ISSUE THREAD

**Issue by sagive** [witochandra/webfeed#8]
I in the process of learning flutter and would really really (*5) appreciate 
a more complete example of a simple rss to "Card" or anything similar.

I searched but couldnt find anything other than the actual final code. 
Any chance of such an example in the near future?

**Comment by witochandra** [comment]
The existing example is consuming RSS & atom feeds in terminal. You can find that in `example` folder.

**Comment by sagive** [comment]
i have seen that but that really the bare minimum.. nm - 10x anyhow.
